server:
  port: 8084
  forward-headers-strategy: framework
eureka:
  instance:
    preferIpAddress: true
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_ADDRESS:https://compatible-finch-tannguyen-14536f90.koyeb.app//eureka}
management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: https://zipkin-am0u.onrender.com/api/v2/spans
springdoc:
  packagesToScan: vn.tannguyen.analytics_service
  cache:
    disabled: true
  version: '@springdoc.version@'
  api-docs:
    version: openapi_3_1
