server:
  port: 8081
  forward-headers-strategy: framework
eureka:
  instance:
    preferIpAddress: true
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_ADDRESS:https://compatible-finch-tannguyen-14536f90.koyeb.app//eureka}
management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: https://zipkin-am0u.onrender.com/api/v2/spans
spring:
  cloud:
    gateway:
      mvc:
        routes:
          - id: analytics-service
            uri: lb://analytics-service
            predicates:
              - Path=/analytics/**
            filters:
              - RewritePath=/analytics/(?<path>.*), /$\{path}
#              - name: CircuitBreaker
#                args:
#                  name: analytics-service
#                  id: analytics-service
#                  fallbackUri: forward:/analyticsServiceFallback
          - id: data-service
            uri: lb://data-service
            predicates:
              - Path=/data/**
            filters:
              - RewritePath=/data/(?<path>.*), /$\{path}
#              - name: CircuitBreaker
#                args:
#                  name: data-service
#                  id: data-service
#                  fallbackUri: forward:/dataServiceFallback
          - id: openapi
            uri: https://tannguyen-gateway-service.azurewebsites.net
            predicates:
              - Path=/v3/api-docs/data,/v3/api-docs/analytics
            filters:
              - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs

springdoc:
  cache:
    disabled: true
  version: '@springdoc.version@'
  swagger-ui:
    enabled: true
    use-root-path: true
  api-docs:
    version: openapi_3_1
