server:
  port: 8081
  forward-headers-strategy: framework
eureka:
  instance:
    preferIpAddress: true
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_ADDRESS:https://compatible-finch-tannguyen-14536f90.koyeb.app//eureka}
management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: https://zipkin-am0u.onrender.com/api/v2/spans
spring:
  cloud:
    gateway:
      mvc:
        routes:
          - id: DATA-SERVICE
            uri: lb://DATA-SERVICE
            predicates:
              - Path=/data-service/**
            filters:
              - name: CircuitBreaker
                args:
                  name: DATA-SERVICE
                  fallbackUri: forward:/dataServiceFallback
          - id: ANALYTICS-SERVICE
            uri: lb://ANALYTICS-SERVICE
            predicates:
              - Path=/analytics-service/**
            filters:
              - name: CircuitBreaker
                args:
                  name: ANALYTICS-SERVICE
                  fallbackUri: forward:/analyticsServiceFallback
          # - id: openapi
          #   uri: http://localhost:${server.port}
          #   predicates:
          #     - Path=/v3/api-docs/**
          #   filters:
          #     - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs
springdoc:
  cache:
    disabled: true
  version: '@springdoc.version@'
  swagger-ui:
    use-root-path: true
  api-docs:
    version: openapi_3_1
