server:
  port: 8080

spring:
  profiles:
    active: native
  application:
    name: config-service

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_ADDRESS:https://compatible-finch-tannguyen-14536f90.koyeb.app//eureka}
  instance:
    preferIpAddress: true

    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}