server:
  port: 8080

spring:
  profiles:
    active: native
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/TanNguyen20/spring-config-data
          default-label: main
          clone-on-start: true

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_ADDRESS:https://compatible-finch-tannguyen-14536f90.koyeb.app//eureka}
  instance:
    preferIpAddress: true